### ISSUE TITLE
Checking for broken links with TravisCI

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#62]
See #19 for fixing all the existing broken links.

Once that's done, we should add a link checker to TravisCI to keep appraised of any broken links (due to external site changes) or bad links in incoming pull request.

@JoaoRodrigues suggested following https://www.jacobtomlinson.co.uk/jekyll/2015/02/18/test-you-jekyll-blog-with-travis-ci/ which suggest this for the ``.travis.yml`` file:

``` yaml
language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
```
